/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryCreateRouteImport } from './routes/history/create'
import { Route as AssetsSymbolRouteImport } from './routes/assets/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCreateRoute = HistoryCreateRouteImport.update({
  id: '/history/create',
  path: '/history/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSymbolRoute = AssetsSymbolRouteImport.update({
  id: '/assets/$symbol',
  path: '/assets/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$symbol': typeof AssetsSymbolRoute
  '/history/create': typeof HistoryCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$symbol': typeof AssetsSymbolRoute
  '/history/create': typeof HistoryCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$symbol': typeof AssetsSymbolRoute
  '/history/create': typeof HistoryCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assets/$symbol' | '/history/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets/$symbol' | '/history/create'
  id: '__root__' | '/' | '/assets/$symbol' | '/history/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsSymbolRoute: typeof AssetsSymbolRoute
  HistoryCreateRoute: typeof HistoryCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/create': {
      id: '/history/create'
      path: '/history/create'
      fullPath: '/history/create'
      preLoaderRoute: typeof HistoryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$symbol': {
      id: '/assets/$symbol'
      path: '/assets/$symbol'
      fullPath: '/assets/$symbol'
      preLoaderRoute: typeof AssetsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsSymbolRoute: AssetsSymbolRoute,
  HistoryCreateRoute: HistoryCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
